version: "3.8"

services:
  db:
    image: postgres:15
    container_name: bread_db
    environment:
      POSTGRES_DB: BreadBd
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - breadnet

  app:
    build: .
    container_name: bread_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    networks:
      - breadnet

volumes:
  pgdata:

networks:
  breadnet:
